# Generated by Django 4.1 on 2022-12-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service_area_id', models.PositiveIntegerField(null=True)),
                ('wa_name', models.CharField(max_length=20, null=True)),
                ('vehicle_id', models.PositiveIntegerField(null=True)),
                ('driver_name', models.CharField(max_length=40, null=True)),
                ('wa_id', models.PositiveIntegerField(null=True)),
                ('scanned_pkgs', models.PositiveIntegerField(null=True)),
                ('delivery_stops', models.PositiveIntegerField(null=True)),
                ('pickup_stops', models.PositiveIntegerField(null=True)),
                ('diff', models.BigIntegerField(null=True)),
                ('actual_delivered_stops', models.PositiveIntegerField(null=True)),
                ('actual_delivered_pkgs', models.PositiveIntegerField(null=True)),
                ('actual_pickup_stops', models.PositiveIntegerField(null=True)),
                ('actual_pickup_packages', models.PositiveIntegerField(null=True)),
                ('ils_percentage', models.FloatField(null=True)),
                ('ils_impact_pkgs', models.PositiveIntegerField(null=True)),
                ('non_delivered_stops', models.PositiveIntegerField(null=True)),
                ('code_85', models.PositiveIntegerField(null=True)),
                ('all_status_code_pkgs', models.PositiveIntegerField(null=True)),
                ('pl_ml', models.PositiveIntegerField(null=True)),
                ('dna', models.PositiveIntegerField(null=True)),
                ('snd_agn', models.PositiveIntegerField(null=True)),
                ('excs', models.PositiveIntegerField(null=True)),
                ('vsa_vs_start_diff', models.PositiveIntegerField(null=True)),
                ('return_scans_percentage', models.FloatField(null=True)),
                ('miles', models.PositiveIntegerField(null=True)),
                ('on_road_hours', models.CharField(max_length=10, null=True)),
                ('on_duty_hours', models.CharField(max_length=10, null=True)),
                ('pot_dot_hrs_viols', models.CharField(max_length=10, null=True)),
                ('next_avail_on_duty', models.CharField(max_length=10, null=True)),
                ('pot_miss_pus', models.CharField(max_length=10, null=True)),
                ('e_and_l_pus', models.CharField(max_length=10, null=True)),
                ('req_sign', models.PositiveIntegerField(null=True)),
                ('date_certain', models.CharField(max_length=10, null=True)),
                ('evening', models.CharField(max_length=10, null=True)),
                ('appt', models.CharField(max_length=10, null=True)),
                ('is_route_split', models.BooleanField(default=False)),
                ('parent_route_id', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ['date', 'vehicle_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyservice',
            constraint=models.UniqueConstraint(fields=('date', 'vehicle_id', 'driver_name', 'actual_delivered_stops', 'parent_route_id'), name='unique_date_vehicle_id'),
        ),
    ]
